name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8 mypy

    - name: Create dummy client_secret.json for tests
      run: |
        echo '{"installed":{"client_id":"dummy","project_id":"dummy","auth_uri":"dummy",
        "token_uri":"dummy","auth_provider_x509_cert_url":"dummy","client_secret":"dummy",
        "redirect_uris":["dummy"]}}' > client_secret.json

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Type check with mypy
      run: |
        mypy main.py

    - name: Test with pytest
      run: |
        pytest test_main.py -v
